// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user-interface.proto

package dgroomes.userinterface;

public final class UserInterfaceProtos {
  private UserInterfaceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InstructionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Instruction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string textContent = 1;</code>
     * @return The textContent.
     */
    java.lang.String getTextContent();
    /**
     * <code>string textContent = 1;</code>
     * @return The bytes for textContent.
     */
    com.google.protobuf.ByteString
        getTextContentBytes();

    /**
     * <code>int32 elementId = 2;</code>
     * @return The elementId.
     */
    int getElementId();

    /**
     * <code>.Instruction.Type type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.Instruction.Type type = 3;</code>
     * @return The type.
     */
    dgroomes.userinterface.UserInterfaceProtos.Instruction.Type getType();
  }
  /**
   * <pre>
   **
   * A naive implementation of a data model that represent user interface (UI) instructions. We are starting with simple
   * "text boxes".
   * </pre>
   *
   * Protobuf type {@code Instruction}
   */
  public static final class Instruction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Instruction)
      InstructionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Instruction.newBuilder() to construct.
    private Instruction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Instruction() {
      textContent_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Instruction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Instruction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              textContent_ = s;
              break;
            }
            case 16: {

              elementId_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dgroomes.userinterface.UserInterfaceProtos.internal_static_Instruction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dgroomes.userinterface.UserInterfaceProtos.internal_static_Instruction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dgroomes.userinterface.UserInterfaceProtos.Instruction.class, dgroomes.userinterface.UserInterfaceProtos.Instruction.Builder.class);
    }

    /**
     * Protobuf enum {@code Instruction.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CREATE = 0;</code>
       */
      CREATE(0),
      /**
       * <code>UPDATE = 1;</code>
       */
      UPDATE(1),
      /**
       * <code>DELETE = 2;</code>
       */
      DELETE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>CREATE = 0;</code>
       */
      public static final int CREATE_VALUE = 0;
      /**
       * <code>UPDATE = 1;</code>
       */
      public static final int UPDATE_VALUE = 1;
      /**
       * <code>DELETE = 2;</code>
       */
      public static final int DELETE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return CREATE;
          case 1: return UPDATE;
          case 2: return DELETE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return dgroomes.userinterface.UserInterfaceProtos.Instruction.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Instruction.Type)
    }

    public static final int TEXTCONTENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object textContent_;
    /**
     * <code>string textContent = 1;</code>
     * @return The textContent.
     */
    @java.lang.Override
    public java.lang.String getTextContent() {
      java.lang.Object ref = textContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        textContent_ = s;
        return s;
      }
    }
    /**
     * <code>string textContent = 1;</code>
     * @return The bytes for textContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextContentBytes() {
      java.lang.Object ref = textContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ELEMENTID_FIELD_NUMBER = 2;
    private int elementId_;
    /**
     * <code>int32 elementId = 2;</code>
     * @return The elementId.
     */
    @java.lang.Override
    public int getElementId() {
      return elementId_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>.Instruction.Type type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.Instruction.Type type = 3;</code>
     * @return The type.
     */
    @java.lang.Override public dgroomes.userinterface.UserInterfaceProtos.Instruction.Type getType() {
      @SuppressWarnings("deprecation")
      dgroomes.userinterface.UserInterfaceProtos.Instruction.Type result = dgroomes.userinterface.UserInterfaceProtos.Instruction.Type.valueOf(type_);
      return result == null ? dgroomes.userinterface.UserInterfaceProtos.Instruction.Type.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTextContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, textContent_);
      }
      if (elementId_ != 0) {
        output.writeInt32(2, elementId_);
      }
      if (type_ != dgroomes.userinterface.UserInterfaceProtos.Instruction.Type.CREATE.getNumber()) {
        output.writeEnum(3, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTextContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, textContent_);
      }
      if (elementId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, elementId_);
      }
      if (type_ != dgroomes.userinterface.UserInterfaceProtos.Instruction.Type.CREATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dgroomes.userinterface.UserInterfaceProtos.Instruction)) {
        return super.equals(obj);
      }
      dgroomes.userinterface.UserInterfaceProtos.Instruction other = (dgroomes.userinterface.UserInterfaceProtos.Instruction) obj;

      if (!getTextContent()
          .equals(other.getTextContent())) return false;
      if (getElementId()
          != other.getElementId()) return false;
      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXTCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getTextContent().hashCode();
      hash = (37 * hash) + ELEMENTID_FIELD_NUMBER;
      hash = (53 * hash) + getElementId();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dgroomes.userinterface.UserInterfaceProtos.Instruction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.Instruction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.Instruction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.Instruction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.Instruction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.Instruction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.Instruction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.Instruction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.Instruction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.Instruction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.Instruction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.Instruction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dgroomes.userinterface.UserInterfaceProtos.Instruction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * A naive implementation of a data model that represent user interface (UI) instructions. We are starting with simple
     * "text boxes".
     * </pre>
     *
     * Protobuf type {@code Instruction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Instruction)
        dgroomes.userinterface.UserInterfaceProtos.InstructionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dgroomes.userinterface.UserInterfaceProtos.internal_static_Instruction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dgroomes.userinterface.UserInterfaceProtos.internal_static_Instruction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dgroomes.userinterface.UserInterfaceProtos.Instruction.class, dgroomes.userinterface.UserInterfaceProtos.Instruction.Builder.class);
      }

      // Construct using dgroomes.userinterface.UserInterfaceProtos.Instruction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        textContent_ = "";

        elementId_ = 0;

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dgroomes.userinterface.UserInterfaceProtos.internal_static_Instruction_descriptor;
      }

      @java.lang.Override
      public dgroomes.userinterface.UserInterfaceProtos.Instruction getDefaultInstanceForType() {
        return dgroomes.userinterface.UserInterfaceProtos.Instruction.getDefaultInstance();
      }

      @java.lang.Override
      public dgroomes.userinterface.UserInterfaceProtos.Instruction build() {
        dgroomes.userinterface.UserInterfaceProtos.Instruction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dgroomes.userinterface.UserInterfaceProtos.Instruction buildPartial() {
        dgroomes.userinterface.UserInterfaceProtos.Instruction result = new dgroomes.userinterface.UserInterfaceProtos.Instruction(this);
        result.textContent_ = textContent_;
        result.elementId_ = elementId_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dgroomes.userinterface.UserInterfaceProtos.Instruction) {
          return mergeFrom((dgroomes.userinterface.UserInterfaceProtos.Instruction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dgroomes.userinterface.UserInterfaceProtos.Instruction other) {
        if (other == dgroomes.userinterface.UserInterfaceProtos.Instruction.getDefaultInstance()) return this;
        if (!other.getTextContent().isEmpty()) {
          textContent_ = other.textContent_;
          onChanged();
        }
        if (other.getElementId() != 0) {
          setElementId(other.getElementId());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dgroomes.userinterface.UserInterfaceProtos.Instruction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dgroomes.userinterface.UserInterfaceProtos.Instruction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object textContent_ = "";
      /**
       * <code>string textContent = 1;</code>
       * @return The textContent.
       */
      public java.lang.String getTextContent() {
        java.lang.Object ref = textContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          textContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string textContent = 1;</code>
       * @return The bytes for textContent.
       */
      public com.google.protobuf.ByteString
          getTextContentBytes() {
        java.lang.Object ref = textContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          textContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string textContent = 1;</code>
       * @param value The textContent to set.
       * @return This builder for chaining.
       */
      public Builder setTextContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        textContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string textContent = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTextContent() {
        
        textContent_ = getDefaultInstance().getTextContent();
        onChanged();
        return this;
      }
      /**
       * <code>string textContent = 1;</code>
       * @param value The bytes for textContent to set.
       * @return This builder for chaining.
       */
      public Builder setTextContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        textContent_ = value;
        onChanged();
        return this;
      }

      private int elementId_ ;
      /**
       * <code>int32 elementId = 2;</code>
       * @return The elementId.
       */
      @java.lang.Override
      public int getElementId() {
        return elementId_;
      }
      /**
       * <code>int32 elementId = 2;</code>
       * @param value The elementId to set.
       * @return This builder for chaining.
       */
      public Builder setElementId(int value) {
        
        elementId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 elementId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearElementId() {
        
        elementId_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.Instruction.Type type = 3;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.Instruction.Type type = 3;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Instruction.Type type = 3;</code>
       * @return The type.
       */
      @java.lang.Override
      public dgroomes.userinterface.UserInterfaceProtos.Instruction.Type getType() {
        @SuppressWarnings("deprecation")
        dgroomes.userinterface.UserInterfaceProtos.Instruction.Type result = dgroomes.userinterface.UserInterfaceProtos.Instruction.Type.valueOf(type_);
        return result == null ? dgroomes.userinterface.UserInterfaceProtos.Instruction.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.Instruction.Type type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(dgroomes.userinterface.UserInterfaceProtos.Instruction.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Instruction.Type type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Instruction)
    }

    // @@protoc_insertion_point(class_scope:Instruction)
    private static final dgroomes.userinterface.UserInterfaceProtos.Instruction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dgroomes.userinterface.UserInterfaceProtos.Instruction();
    }

    public static dgroomes.userinterface.UserInterfaceProtos.Instruction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Instruction>
        PARSER = new com.google.protobuf.AbstractParser<Instruction>() {
      @java.lang.Override
      public Instruction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Instruction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Instruction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Instruction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dgroomes.userinterface.UserInterfaceProtos.Instruction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 clientId = 1;</code>
     * @return The clientId.
     */
    int getClientId();
  }
  /**
   * <pre>
   **
   * This is mostly unused. We just are not allowed to define rpc methods without parameters.
   * </pre>
   *
   * Protobuf type {@code ClientRequest}
   */
  public static final class ClientRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientRequest)
      ClientRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientRequest.newBuilder() to construct.
    private ClientRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClientRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              clientId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dgroomes.userinterface.UserInterfaceProtos.internal_static_ClientRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dgroomes.userinterface.UserInterfaceProtos.internal_static_ClientRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dgroomes.userinterface.UserInterfaceProtos.ClientRequest.class, dgroomes.userinterface.UserInterfaceProtos.ClientRequest.Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private int clientId_;
    /**
     * <code>int32 clientId = 1;</code>
     * @return The clientId.
     */
    @java.lang.Override
    public int getClientId() {
      return clientId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientId_ != 0) {
        output.writeInt32(1, clientId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clientId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dgroomes.userinterface.UserInterfaceProtos.ClientRequest)) {
        return super.equals(obj);
      }
      dgroomes.userinterface.UserInterfaceProtos.ClientRequest other = (dgroomes.userinterface.UserInterfaceProtos.ClientRequest) obj;

      if (getClientId()
          != other.getClientId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dgroomes.userinterface.UserInterfaceProtos.ClientRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * This is mostly unused. We just are not allowed to define rpc methods without parameters.
     * </pre>
     *
     * Protobuf type {@code ClientRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientRequest)
        dgroomes.userinterface.UserInterfaceProtos.ClientRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dgroomes.userinterface.UserInterfaceProtos.internal_static_ClientRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dgroomes.userinterface.UserInterfaceProtos.internal_static_ClientRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dgroomes.userinterface.UserInterfaceProtos.ClientRequest.class, dgroomes.userinterface.UserInterfaceProtos.ClientRequest.Builder.class);
      }

      // Construct using dgroomes.userinterface.UserInterfaceProtos.ClientRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dgroomes.userinterface.UserInterfaceProtos.internal_static_ClientRequest_descriptor;
      }

      @java.lang.Override
      public dgroomes.userinterface.UserInterfaceProtos.ClientRequest getDefaultInstanceForType() {
        return dgroomes.userinterface.UserInterfaceProtos.ClientRequest.getDefaultInstance();
      }

      @java.lang.Override
      public dgroomes.userinterface.UserInterfaceProtos.ClientRequest build() {
        dgroomes.userinterface.UserInterfaceProtos.ClientRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dgroomes.userinterface.UserInterfaceProtos.ClientRequest buildPartial() {
        dgroomes.userinterface.UserInterfaceProtos.ClientRequest result = new dgroomes.userinterface.UserInterfaceProtos.ClientRequest(this);
        result.clientId_ = clientId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dgroomes.userinterface.UserInterfaceProtos.ClientRequest) {
          return mergeFrom((dgroomes.userinterface.UserInterfaceProtos.ClientRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dgroomes.userinterface.UserInterfaceProtos.ClientRequest other) {
        if (other == dgroomes.userinterface.UserInterfaceProtos.ClientRequest.getDefaultInstance()) return this;
        if (other.getClientId() != 0) {
          setClientId(other.getClientId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dgroomes.userinterface.UserInterfaceProtos.ClientRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dgroomes.userinterface.UserInterfaceProtos.ClientRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int clientId_ ;
      /**
       * <code>int32 clientId = 1;</code>
       * @return The clientId.
       */
      @java.lang.Override
      public int getClientId() {
        return clientId_;
      }
      /**
       * <code>int32 clientId = 1;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(int value) {
        
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 clientId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientRequest)
    }

    // @@protoc_insertion_point(class_scope:ClientRequest)
    private static final dgroomes.userinterface.UserInterfaceProtos.ClientRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dgroomes.userinterface.UserInterfaceProtos.ClientRequest();
    }

    public static dgroomes.userinterface.UserInterfaceProtos.ClientRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientRequest>
        PARSER = new com.google.protobuf.AbstractParser<ClientRequest>() {
      @java.lang.Override
      public ClientRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dgroomes.userinterface.UserInterfaceProtos.ClientRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Instruction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Instruction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024user-interface.proto\"\202\001\n\013Instruction\022\023" +
      "\n\013textContent\030\001 \001(\t\022\021\n\telementId\030\002 \001(\005\022\037" +
      "\n\004type\030\003 \001(\0162\021.Instruction.Type\"*\n\004Type\022" +
      "\n\n\006CREATE\020\000\022\n\n\006UPDATE\020\001\022\n\n\006DELETE\020\002\"!\n\rC" +
      "lientRequest\022\020\n\010clientId\030\001 \001(\0052K\n\023UserIn" +
      "terfaceDriver\0224\n\020NextInstructions\022\016.Clie" +
      "ntRequest\032\014.Instruction\"\0000\001B-\n\026dgroomes." +
      "userinterfaceB\023UserInterfaceProtosb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Instruction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Instruction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Instruction_descriptor,
        new java.lang.String[] { "TextContent", "ElementId", "Type", });
    internal_static_ClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientRequest_descriptor,
        new java.lang.String[] { "ClientId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
